name: invoice
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  supabase_flutter: 0.3.3
  google_fonts: 3.0.1
  hexcolor: 2.0.7
  lottie: 1.4.2
  splashscreen: 1.3.5
  intl: 0.17.0
  sticky_and_expandable_list: 1.1.2
  expandable: 5.0.1
  dropdown_search: 5.0.2
  iconly: 1.0.1
  signature: 5.2.1
  syncfusion_flutter_signaturepad: 20.2.48
  provider: 6.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

